return {
    -- every line should be same width without escaped \
    header = {
        type = "text",
        oldfiles_directory = false,
        align = "center",
        fold_section = false,
        title = "Header",
        margin = 5,
        content = {
            "                                                               ",
            "                                                               ",
            "                                                               ",
            "                                                               ",
            "                                                               ",
            "                                                               ",
            "                                                               ",
            "                                                               ",
            "                                                               ",
            "                                                               ",
            "                                                               ",
            "                                                               ",
            "                                                               ",
            "                                                               ",
            "                                                               ",
            "                                                               ",
            "                                                               ",
            "                                                               ",
            "                                                               ",
            "                                                               ",
            "                                                               ",
            "                                                               ",
            "                                                               ",
            "                                                               ",
            "                                                               ",
            "                                                               ",
            "     ███████╗██╗██████╗ ███████╗███████╗ ██████╗ ██╗  ██╗      ",
            "     ██╔════╝██║██╔══██╗██╔════╝██╔════╝██╔═══██╗╚██╗██╔╝      ",
            "     █████╗  ██║██████╔╝█████╗  █████╗  ██║   ██║ ╚███╔╝       ",
            "     ██╔══╝  ██║██╔══██╗██╔══╝  ██╔══╝  ██║   ██║ ██╔██╗       ",
            "     ██║     ██║██║  ██║███████╗██║     ╚██████╔╝██╔╝ ██╗      ",
            "     ╚═╝     ╚═╝╚═╝  ╚═╝╚══════╝╚═╝      ╚═════╝ ╚═╝  ╚═╝      ",
        },
        highlight = "Statement",
        default_color = "",
    },
    footer = {
        type = "text",
        align = "center",
        fold_section = false,
        title = "Footer",
        margin = 1,
        content = { "be kind to everyone, including yourself <3" },
        highlight = "Number",
        default_color = "",
    },
    options = {
        cursor_column = 0.5,
        empty_lines_between_mappings = true,
        disable_statuslines = true,
        paddings = { 1, 1, 1 },
    },
    parts = { "header", "footer" },
}
