long_kernel = true

physical_cores = true

theme = "Catppuccin"
#theme = "Hydrogen"

show = [
"Machine",
"Kernel",
"DesktopEnvironment",
"WindowManager",
"Packages", 
#"Terminal", 
"Shell", 
"Uptime", 
"Processor",
"ProcessorLoad",
"Memory",
"Battery",
]
