set -g default-terminal "screen-256color"
set -ga terminal-overrides ",screen-256color:Tc"

unbind r
bind r \
        source-file ~/.config/tmux/tmux.conf \;\
        display 'Reloaded tmux config'

set -g status-bg "#1e1e2e"
set -g status-fg "#cdd6f4"


set-option -g status-left "\
#[fg=#11111b, bg=#cba6f7] 󰖲 #S \
#[fg=#cba6f7, bg=#1e1e2e] \
"


set -g status-right "\
#[fg=#cba6f7]\
#[fg=#11111b, bg=#cba6f7] %a %d %b \
#[fg=#cba6f7]\
#[fg=#11111b] %H:%M \
"

set-window-option -g window-status-current-format "\
#[fg=#cba6f7]\
#[fg=#11111b, bg=#cba6f7] #I* \
#[fg=#cba6f7]|\
#[fg=#11111b, bold] #W \
#[fg=#cba6f7, bg=#1e1e2e]\
"

set-window-option -g window-status-format "\
#[fg=#11111b]\
#[fg=#cdd6f4, bg=#11111b] #I \
#[fg=#11111b]|\
#[fg=#cdd6f4] #W \
#[fg=#11111b, bg=#1e1e2e]\
"

#[fg=colour246, bg=colour237,bold] 
#[fg=colour248, bg=colour239]

